# Generated by Django 3.1.7 on 2022-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_subject_and_university_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_and_University_Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(max_length=100, null=True)),
                ('student_university', models.CharField(max_length=100, null=True)),
                ('student_subject', models.CharField(max_length=100, null=True)),
                ('ranking_score', models.CharField(max_length=100, null=True)),
                ('ranking_registration_number', models.CharField(max_length=100, null=True)),
                ('ranking_username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
