# Generated by Django 3.1.7 on 2022-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_subject_and_university_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_and_university_model2',
            name='ranking_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
