# Generated by Django 3.1.7 on 2022-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BRUR_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BSFMSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BSMRSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='COU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JKKNIU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JNU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JUST_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MBSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PUST_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RMSTU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RUB_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SHU_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SUST_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('combine', models.CharField(max_length=100)),
            ],
        ),
    ]
