# Generated by Django 3.1.7 on 2022-03-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BDU_Model',
        ),
        migrations.DeleteModel(
            name='BRUR_Model',
        ),
        migrations.DeleteModel(
            name='BSFMSTU_Model',
        ),
        migrations.DeleteModel(
            name='BSMRSTU_Model',
        ),
        migrations.DeleteModel(
            name='BU_Model',
        ),
        migrations.DeleteModel(
            name='COU_Model',
        ),
        migrations.DeleteModel(
            name='HSTU_Model',
        ),
        migrations.DeleteModel(
            name='IU_Model',
        ),
        migrations.DeleteModel(
            name='JKKNIU_Model',
        ),
        migrations.DeleteModel(
            name='JNU_Model',
        ),
        migrations.DeleteModel(
            name='JUST_Model',
        ),
        migrations.DeleteModel(
            name='KU_Model',
        ),
        migrations.DeleteModel(
            name='MBSTU_Model',
        ),
        migrations.DeleteModel(
            name='NSTU_Model',
        ),
        migrations.DeleteModel(
            name='PSTU_Model',
        ),
        migrations.DeleteModel(
            name='PUST_Model',
        ),
        migrations.DeleteModel(
            name='RMSTU_Model',
        ),
        migrations.DeleteModel(
            name='RUB_Model',
        ),
        migrations.DeleteModel(
            name='SHU_Model',
        ),
        migrations.DeleteModel(
            name='SUST_Model',
        ),
    ]
