# Generated by Django 3.1.7 on 2022-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20220313_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_Subject_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, null=True)),
                ('university_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
