# Generated by Django 3.1.7 on 2022-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_selected_subject_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_subject_model',
            name='choosen_number',
            field=models.IntegerField(null=True),
        ),
    ]
