# Generated by Django 3.1.7 on 2022-04-04 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('student_contact_no', models.IntegerField()),
                ('parent_contact', models.IntegerField()),
                ('student_email', models.EmailField(max_length=70, unique=True)),
                ('relationship', models.CharField(max_length=100)),
                ('present_adress', models.CharField(max_length=100)),
                ('parmanent_adress', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('postal_zip', models.IntegerField()),
                ('exam_namessc', models.CharField(max_length=100)),
                ('passing_yearssc', models.IntegerField()),
                ('gpassc', models.CharField(max_length=100)),
                ('ssc_roll_number', models.IntegerField()),
                ('ssc_registration_number', models.IntegerField()),
                ('boardssc', models.CharField(max_length=100)),
                ('sscgroup', models.CharField(max_length=100, null=True)),
                ('exam_namehsc', models.CharField(max_length=100)),
                ('passing_yearhsc', models.IntegerField()),
                ('gpahsc', models.CharField(max_length=100)),
                ('hsc_roll_number', models.IntegerField()),
                ('hsc_registration_number', models.IntegerField()),
                ('boardhsc', models.CharField(max_length=100)),
                ('hsc_group', models.CharField(max_length=100, null=True)),
                ('exam_score', models.FloatField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
