# Generated by Django 3.1.7 on 2022-04-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_model',
            name='exam_score',
        ),
    ]
