# Generated by Django 3.1.7 on 2022-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_registration_model_exam_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_model',
            name='exam_score',
            field=models.FloatField(null=True),
        ),
    ]
